### ISSUE TITLE
[Win10] Python is not installed

### ISSUE THREAD

**Issue by luxxxxy** [Greg0109/ForwardNotifier#4]
```
Installing ForwardNotifier. . .
Checking if python is installed.
Python is not installed, installing python... please wait.
Download completed. Running installer.
```

I very clearly have python installed. Python 2.7, 3.6, and 3.8 are installed. The `py` launcher is installed and the 3.8 `python.exe` is in PATH. Are you checking for `C:\Python` or something?

**Comment by Greg0109** [comment]
What installer are you using?

Gregorio Rabago Sainz

**Comment by luxxxxy** [comment]
![explorer_CcIksbi41F](https://user-images.githubusercontent.com/65794972/83331011-2b49b680-a261-11ea-8fde-e6f6fd6c2334.png)
![SystemPropertiesAdvanced_ndtFmLC3yb](https://user-images.githubusercontent.com/65794972/83331015-36044b80-a261-11ea-98a4-a8e59556be5d.png)
![SystemPropertiesAdvanced_cSyQBsirq8](https://user-images.githubusercontent.com/65794972/83331021-41577700-a261-11ea-98a2-b2c9479117cb.png)

I am using the `ForwardNotifierSetup.exe` from the repo.

**Comment by Greg0109** [comment]
I’ll talk with the windows dev. Is the tweak working tho?

Gregorio Rabago Sainz

**Comment by luxxxxy** [comment]
i mean I can't really test the SENDING functionality but the settings menu works

**Comment by Greg0109** [comment]
Why cannot you test it? The installer installed the rest of the files right?

Gregorio Rabago Sainz

**Comment by luxxxxy** [comment]
![explorer_95rvMZXYE8](https://user-images.githubusercontent.com/65794972/83331246-e0c93980-a262-11ea-9481-c32e6595dc2e.png)
![ForwardNotifierSetup_RCh0NbsUcZ](https://user-images.githubusercontent.com/65794972/83331247-e888de00-a262-11ea-913b-943026b38fad.png)

**Comment by Greg0109** [comment]
That literally gives me 0 info. Yes, I know it doesn’t detect your python installation.
Why cannot you test the tweak? The installer should install the rest of the files, does it not? Does it give you any errors?

Gregorio Rabago Sainz

**Comment by luxxxxy** [comment]
Where would the files it installed even be?? There's nothing new in `Documents/ForwardNotifier`, nothing in AppData, etc

**Comment by Greg0109** [comment]
Check C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Startup

Gregorio Rabago Sainz

**Comment by Greg0109** [comment]
It’s a file called “Server.pyw”

Gregorio Rabago Sainz

**Comment by luxxxxy** [comment]
It wasn't there.

I however did download the `ForwardNotifierServer.py` from the repo, and ran it using `py -3`.

It runs (`Starting httpd on port 8000 ...`), however it does not seem to be receiving any notifications, even though the IP is set right.

I am not sure if I have configured.

By the way, I apologize if this issue is simple and I'm annoying you.

**Comment by Greg0109** [comment]
Did you ran the installer as administrator?

Gregorio Rabago Sainz

**Comment by luxxxxy** [comment]
Yes.

**Comment by Greg0109** [comment]
Unless you haven’t enabled the tweak in the CC then I’m not sure why it’s not working for you

Gregorio Rabago Sainz

**Comment by xIGBClutchIx** [comment]
I also seem to be having the same issue too. Possibly because I also have python installed in a custom location - "C:\Programming\Python\Python38"
